name: Deploy Node.js to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SH_KEY }}
        script: |
          cd /home/ec2-user/my-node-api
          git pull origin main || echo "Git repo not set. Skipping pull"
          npm install
          pm2 restart index || pm2 start index.js --name index
